### ISSUE TITLE
Error when executing `mvn clean install`

### ISSUE THREAD

**Issue by joyheron** [complate/complate-java#13]
I get the following error when executing `mvn clean install`

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce) on project complate-core: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]`

**Comment by mvitz** [comment]
Could you please update your local clone via `git pull` (note that I did some force pushes within the last hour) and try again?

If it fails again it would be nice to get some more output to see what rules may have failed.

**Comment by joyheron** [comment]
Thank you for the quick response!

`./mvnw clean install` worked directly

for my local maven installation I got the warning

`[WARNING] Rule 3: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.3.9 is not in the allowed range 3.6.`

but after upgrading my local maven installation to `3.6.X` I am able to build successfully.

**Comment by joyheron** [comment]
From my side, this issue can be closed.
